import type { MockSku } from "./types";

/**
 * Fonte única de SKUs mockados — Pedidos, Anúncios e Estoque importam daqui
 * (antes cada um tinha sua própria cópia; unificado nesta etapa). Conecta
 * com `Sku` real na etapa de integrações.
 */
export const MOCK_SKUS: MockSku[] = [
  {
    id: "sku_1",
    code: "KOC-001",
    name: "Kit Organizador de Cozinha 5 Peças",
    costAmount: 42.9,
    packagingCostAmount: 3.5,
    stockLocal: 40,
    stockFull: 60,
    lowStockThreshold: 20,
    imageColor: "bg-chart-1/20",
    active: true,
  },
  {
    id: "sku_2",
    code: "STV-002",
    name: "Suporte de TV Preto",
    costAmount: 38.5,
    packagingCostAmount: 4.2,
    stockLocal: 3,
    stockFull: 0,
    lowStockThreshold: 10,
    imageColor: "bg-chart-2/20",
    active: true,
  },
  {
    id: "sku_3",
    code: "OGT-003",
    name: "Organizador de Geladeira Transparente",
    costAmount: 21.3,
    packagingCostAmount: 2.1,
    stockLocal: 8,
    stockFull: 4,
    lowStockThreshold: 15,
    imageColor: "bg-chart-3/20",
    active: true,
  },
  {
    id: "sku_4",
    code: "PFB-004",
    name: "Prateleira Flutuante Branca 60cm",
    costAmount: 27.8,
    packagingCostAmount: 5.0,
    stockLocal: 0,
    stockFull: 0,
    lowStockThreshold: 10,
    imageColor: "bg-chart-4/20",
    active: true,
  },
  {
    id: "sku_5",
    code: "CER-005",
    name: "Cesto Organizador de Roupas",
    costAmount: 19.9,
    packagingCostAmount: 2.8,
    stockLocal: 30,
    stockFull: 20,
    lowStockThreshold: 15,
    imageColor: "bg-chart-5/20",
    active: true,
  },
  {
    id: "sku_6",
    code: "PTG-006",
    name: "Porta Temperos Giratório",
    costAmount: 24.6,
    packagingCostAmount: 3.0,
    stockLocal: 2,
    stockFull: 1,
    lowStockThreshold: 10,
    imageColor: "bg-chart-1/20",
    active: true,
  },
  {
    id: "sku_7",
    code: "EDL-007",
    name: "Escorredor de Louça Inox",
    costAmount: 55.0,
    packagingCostAmount: 6.5,
    stockLocal: 25,
    stockFull: 15,
    lowStockThreshold: 12,
    imageColor: "bg-chart-3/20",
    active: true,
  },
  {
    id: "sku_8",
    code: "SPR-008",
    name: "Suporte para Panelas Retrátil",
    costAmount: 33.2,
    packagingCostAmount: 4.0,
    stockLocal: 6,
    stockFull: 2,
    lowStockThreshold: 12,
    imageColor: "bg-chart-4/20",
    active: true,
  },
];
