import type { MockListing } from "./types";

const ACCOUNT_LABEL = {
  MERCADO_LIVRE: "Loja da Maria · Mercado Livre",
  SHOPEE: "Loja da Maria · Shopee",
} as const;

function daysAgo(d: number): Date {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000);
}

/** Tudo mockado — conecta com Listing/ListingSku reais na etapa de integrações. */
export const MOCK_LISTINGS: MockListing[] = [
  {
    id: "lst_1",
    externalId: "ML-1234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Kit Organizador de Cozinha 5 Peças",
    thumbnailColor: "bg-chart-1/20",
    price: 189.9,
    status: "ACTIVE",
    listingKind: "Premium",
    logisticsType: "Full",
    channel: "Ads",
    tag: "Linha Cozinha",
    fromCatalog: true,
    skuCode: "KOC-001",
    competitivePosition: "WINNING",
    availableQuantity: 40,
    salesCount: 28,
    revenue: 5317.2,
    netReceived: 4571.4,
    hasPackagingCost: true,
    createdAt: daysAgo(120),
  },
  {
    id: "lst_2",
    externalId: "ML-2234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Suporte de TV Preto Articulado",
    thumbnailColor: "bg-chart-2/20",
    price: 99.9,
    status: "ACTIVE",
    listingKind: "Clássico",
    logisticsType: "Correios",
    channel: "Ads",
    tag: null,
    fromCatalog: false,
    skuCode: "STV-002",
    competitivePosition: "LOSING",
    availableQuantity: 3,
    salesCount: 9,
    revenue: 899.1,
    netReceived: 743.6,
    hasPackagingCost: true,
    createdAt: daysAgo(200),
  },
  {
    id: "lst_3",
    externalId: "SHP-3234567890",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    title: "Organizador de Geladeira Transparente 3L",
    thumbnailColor: "bg-chart-3/20",
    price: 69.9,
    status: "ACTIVE",
    listingKind: "Padrão",
    logisticsType: "Correios",
    channel: "Orgânico",
    tag: "Linha Cozinha",
    fromCatalog: true,
    skuCode: "OGT-003",
    competitivePosition: "WINNING",
    availableQuantity: 12,
    salesCount: 14,
    revenue: 978.6,
    netReceived: 856.1,
    hasPackagingCost: true,
    createdAt: daysAgo(90),
  },
  {
    id: "lst_4",
    externalId: "ML-4234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Prateleira Flutuante Branca 60cm",
    thumbnailColor: "bg-chart-4/20",
    price: 124.85,
    status: "PAUSED",
    listingKind: "Clássico",
    logisticsType: "Full",
    channel: "Orgânico",
    tag: null,
    fromCatalog: false,
    skuCode: null,
    competitivePosition: "UNKNOWN",
    availableQuantity: 0,
    salesCount: 6,
    revenue: 749.1,
    netReceived: 623.9,
    hasPackagingCost: false,
    createdAt: daysAgo(60),
  },
  {
    id: "lst_5",
    externalId: "SHP-5234567890",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    title: "Cesto Organizador de Roupas Cinza",
    thumbnailColor: "bg-chart-5/20",
    price: 64.9,
    status: "ACTIVE",
    listingKind: "Impulsionado",
    logisticsType: "Coleta",
    channel: "Ads",
    tag: "Linha Quarto",
    fromCatalog: true,
    skuCode: "CER-005",
    competitivePosition: "WINNING",
    availableQuantity: 50,
    salesCount: 22,
    revenue: 1427.8,
    netReceived: 1231.5,
    hasPackagingCost: true,
    createdAt: daysAgo(150),
  },
  {
    id: "lst_6",
    externalId: "ML-6234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Porta Temperos Giratório 16 Potes",
    thumbnailColor: "bg-chart-1/20",
    price: 64.9,
    status: "ACTIVE",
    listingKind: "Clássico",
    logisticsType: "Correios",
    channel: "Orgânico",
    tag: null,
    fromCatalog: true,
    skuCode: "PTG-006",
    competitivePosition: "LOSING",
    availableQuantity: 3,
    salesCount: 11,
    revenue: 713.9,
    netReceived: 598.2,
    hasPackagingCost: true,
    createdAt: daysAgo(80),
  },
  {
    id: "lst_7",
    externalId: "ML-7234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Escorredor de Louça Inox 2 Andares",
    thumbnailColor: "bg-chart-3/20",
    price: 149.9,
    status: "ACTIVE",
    listingKind: "Premium",
    logisticsType: "Full",
    channel: "Ads",
    tag: "Linha Cozinha",
    fromCatalog: true,
    skuCode: "EDL-007",
    competitivePosition: "WINNING",
    availableQuantity: 25,
    salesCount: 17,
    revenue: 2548.3,
    netReceived: 2178.9,
    hasPackagingCost: true,
    createdAt: daysAgo(45),
  },
  {
    id: "lst_8",
    externalId: "SHP-8234567890",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    title: "Suporte para Panelas Retrátil Inox",
    thumbnailColor: "bg-chart-4/20",
    price: 79.9,
    status: "UNDER_REVIEW",
    listingKind: "Padrão",
    logisticsType: "Correios",
    channel: "Orgânico",
    tag: null,
    fromCatalog: false,
    skuCode: "SPR-008",
    competitivePosition: "UNKNOWN",
    availableQuantity: 8,
    salesCount: 2,
    revenue: 159.8,
    netReceived: 132.4,
    hasPackagingCost: false,
    createdAt: daysAgo(10),
  },
  {
    id: "lst_9",
    externalId: "ML-9234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Kit 3 Potes Herméticos para Mantimentos",
    thumbnailColor: "bg-chart-2/20",
    price: 89.9,
    status: "ACTIVE",
    listingKind: "Clássico",
    logisticsType: "Full",
    channel: "Orgânico",
    tag: "Linha Cozinha",
    fromCatalog: false,
    skuCode: null,
    competitivePosition: "LOSING",
    availableQuantity: 18,
    salesCount: 5,
    revenue: 449.5,
    netReceived: 372.7,
    hasPackagingCost: false,
    createdAt: daysAgo(30),
  },
  {
    id: "lst_10",
    externalId: "SHP-10234567890",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    title: "Organizador de Geladeira Transparente 5L",
    thumbnailColor: "bg-chart-3/20",
    price: 79.9,
    status: "ACTIVE",
    listingKind: "Impulsionado",
    logisticsType: "Correios",
    channel: "Ads",
    tag: "Linha Cozinha",
    fromCatalog: true,
    skuCode: "OGT-003",
    competitivePosition: "LOSING",
    availableQuantity: 12,
    salesCount: 8,
    revenue: 639.2,
    netReceived: 543.8,
    hasPackagingCost: true,
    createdAt: daysAgo(70),
  },
  {
    id: "lst_11",
    externalId: "ML-11234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Cesto Organizador de Roupas Bege",
    thumbnailColor: "bg-chart-5/20",
    price: 59.9,
    status: "CLOSED",
    listingKind: "Clássico",
    logisticsType: "Full",
    channel: "Orgânico",
    tag: "Linha Quarto",
    fromCatalog: true,
    skuCode: "CER-005",
    competitivePosition: "UNKNOWN",
    availableQuantity: 0,
    salesCount: 31,
    revenue: 1856.9,
    netReceived: 1598.1,
    hasPackagingCost: true,
    createdAt: daysAgo(300),
  },
  {
    id: "lst_12",
    externalId: "ML-12234567890",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    title: "Prateleira Flutuante Preta 80cm",
    thumbnailColor: "bg-chart-4/20",
    price: 139.9,
    status: "ACTIVE",
    listingKind: "Premium",
    logisticsType: "Full",
    channel: "Ads",
    tag: null,
    fromCatalog: false,
    skuCode: null,
    competitivePosition: "WINNING",
    availableQuantity: 22,
    salesCount: 13,
    revenue: 1818.7,
    netReceived: 1552.3,
    hasPackagingCost: false,
    createdAt: daysAgo(20),
  },
];
