import { MOCK_SKUS } from "@/features/catalog/mock-data";
import type { MockOrder, OrderStatus } from "./types";

/**
 * Tudo neste arquivo é dado FAKE — conecta com Order/OrderItem/Sku reais
 * numa etapa futura de integrações (mesma observação do Dashboard).
 */

// Reexportado (agora vem de features/catalog, fonte única de SKUs mockados
// compartilhada com Anúncios e Estoque — Etapa 5).
export { MOCK_SKUS };

const ACCOUNT_LABEL: Record<"MERCADO_LIVRE" | "SHOPEE", string> = {
  MERCADO_LIVRE: "Loja da Maria · Mercado Livre",
  SHOPEE: "Loja da Maria · Shopee",
};

function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 60 * 60 * 1000);
}

function daysFromNow(d: number): Date {
  return new Date(Date.now() + d * 24 * 60 * 60 * 1000);
}

// Classes completas (não concatenadas em runtime) — o scanner do Tailwind
// só detecta tokens de classe que aparecem literalmente no código-fonte;
// montar "bg-chart-1" + "/20" em runtime não geraria a classe no build.
const THUMB_COLORS = ["bg-chart-1/20", "bg-chart-2/20", "bg-chart-3/20", "bg-chart-4/20", "bg-chart-5/20"];

let thumbIndex = 0;
function nextThumb(): string {
  const color = THUMB_COLORS[thumbIndex % THUMB_COLORS.length];
  thumbIndex += 1;
  return color;
}

export const MOCK_ORDERS: MockOrder[] = [
  {
    id: "ord_1",
    externalId: "ML-20260812093344",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Orgânico",
    status: "DELIVERED",
    shippingStage: "DELIVERED",
    shippingType: "Full",
    totalAmount: 189.9,
    feeAmount: 22.79,
    shippingCost: 0,
    taxAmount: 11.39,
    costAmount: 42.9,
    items: [
      { id: "it_1", title: "Kit Organizador de Cozinha 5 Peças", skuCode: "KOC-001", fromCatalog: true, quantity: 1, unitPrice: 189.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(30),
    paymentMethod: "Cartão de crédito (parcelado 3x)",
    payoutForecast: daysFromNow(2),
    buyerName: "Camila R.",
    address: "São Paulo · SP",
  },
  {
    id: "ord_2",
    externalId: "SHP-88213640912",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    channel: "Ads",
    status: "SHIPPED",
    shippingStage: "IN_TRANSIT",
    shippingType: "Correios",
    totalAmount: 134.8,
    feeAmount: 14.85,
    shippingCost: 12.9,
    taxAmount: 8.09,
    costAmount: 21.3 + 24.6,
    items: [
      { id: "it_2a", title: "Organizador de Geladeira Transparente", skuCode: "OGT-003", fromCatalog: true, quantity: 1, unitPrice: 69.9, thumbnailColor: nextThumb() },
      { id: "it_2b", title: "Porta Temperos Giratório", skuCode: "PTG-006", fromCatalog: true, quantity: 1, unitPrice: 64.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(18),
    paymentMethod: "Pix",
    payoutForecast: daysFromNow(4),
    buyerName: "Rodrigo A.",
    address: "Curitiba · PR",
  },
  {
    id: "ord_3",
    externalId: "ML-20260817145501",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Orgânico",
    status: "IN_PREPARATION",
    shippingStage: "READY",
    shippingType: "Correios",
    totalAmount: 79.9,
    feeAmount: 9.59,
    shippingCost: 15.9,
    taxAmount: 4.79,
    costAmount: null,
    items: [
      { id: "it_3", title: "Cesto Organizador de Roupas", skuCode: null, fromCatalog: false, quantity: 1, unitPrice: 79.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(5),
    paymentMethod: "Cartão de crédito (à vista)",
    payoutForecast: daysFromNow(6),
    buyerName: "Fernanda L.",
    address: "Belo Horizonte · MG",
  },
  {
    id: "ord_4",
    externalId: "ML-20260816102210",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Ads",
    status: "PAID",
    shippingStage: null,
    shippingType: "Full",
    totalAmount: 249.7,
    feeAmount: 29.96,
    shippingCost: 0,
    taxAmount: 14.98,
    costAmount: null,
    items: [
      { id: "it_4", title: "Prateleira Flutuante Branca 60cm", skuCode: null, fromCatalog: false, quantity: 2, unitPrice: 124.85, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(9),
    paymentMethod: "Mercado Pago (saldo)",
    payoutForecast: daysFromNow(3),
    buyerName: "Juliana P.",
    address: "Porto Alegre · RS",
  },
  {
    id: "ord_5",
    externalId: "SHP-88209981274",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    channel: "Ads",
    status: "DELIVERED",
    shippingStage: "DELIVERED",
    shippingType: "Correios",
    totalAmount: 99.9,
    feeAmount: 11.99,
    // Frete alto (o seller passou a arcar com o frete grátis promocional
    // depois do "ajuste de frete" citado no alerta do Dashboard) empurra a
    // margem pra negativa (~-8%) — mesmo anúncio, mesma margem do alerta
    // "Margem negativa" mockado no Dashboard (continuidade proposital).
    shippingCost: 51.4,
    taxAmount: 5.99,
    costAmount: 38.5,
    items: [
      { id: "it_5", title: "Suporte de TV Preto", skuCode: "STV-002", fromCatalog: true, quantity: 1, unitPrice: 99.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(60),
    paymentMethod: "Cartão de crédito (parcelado 2x)",
    payoutForecast: daysFromNow(-1),
    buyerName: "Bruno S.",
    address: "Recife · PE",
  },
  {
    id: "ord_6",
    externalId: "ML-20260818071502",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Orgânico",
    status: "PENDING",
    shippingStage: null,
    shippingType: "Correios",
    totalAmount: 64.9,
    feeAmount: 7.79,
    shippingCost: 14.9,
    taxAmount: 3.89,
    costAmount: 19.9,
    items: [
      { id: "it_6", title: "Cesto Organizador de Roupas", skuCode: "CER-005", fromCatalog: true, quantity: 1, unitPrice: 64.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(1),
    paymentMethod: "Pix",
    payoutForecast: daysFromNow(7),
    buyerName: "Aguardando pagamento",
    address: "—",
  },
  {
    id: "ord_7",
    externalId: "ML-20260810161822",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Orgânico",
    status: "CANCELED",
    shippingStage: null,
    shippingType: "Correios",
    totalAmount: 79.9,
    feeAmount: 0,
    shippingCost: 0,
    taxAmount: 0,
    costAmount: 21.3,
    items: [
      { id: "it_7", title: "Organizador de Geladeira Transparente", skuCode: "OGT-003", fromCatalog: true, quantity: 1, unitPrice: 79.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(190),
    paymentMethod: "Cartão de crédito (à vista)",
    payoutForecast: daysFromNow(-5),
    buyerName: "Pedro M.",
    address: "Salvador · BA",
  },
  {
    id: "ord_8",
    externalId: "SHP-88198821035",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    channel: "Orgânico",
    status: "RETURNED",
    shippingStage: null,
    shippingType: "Correios",
    totalAmount: 64.9,
    feeAmount: 7.79,
    shippingCost: 12.9,
    taxAmount: 3.89,
    costAmount: 24.6,
    items: [
      { id: "it_8", title: "Porta Temperos Giratório", skuCode: "PTG-006", fromCatalog: true, quantity: 1, unitPrice: 64.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(240),
    paymentMethod: "Pix",
    payoutForecast: daysFromNow(-8),
    buyerName: "Larissa T.",
    address: "Fortaleza · CE",
  },
  {
    id: "ord_9",
    externalId: "EXT-000114",
    provider: "EXTERNAL",
    accountLabel: "Venda externa",
    channel: "Externo",
    status: "DELIVERED",
    shippingStage: "DELIVERED",
    shippingType: "Combinado com o comprador",
    totalAmount: 220,
    feeAmount: 0,
    shippingCost: 0,
    taxAmount: 0,
    costAmount: 42.9 + 27.8,
    items: [
      { id: "it_9a", title: "Kit Organizador de Cozinha 5 Peças", skuCode: "KOC-001", fromCatalog: true, quantity: 1, unitPrice: 130, thumbnailColor: nextThumb() },
      { id: "it_9b", title: "Prateleira Flutuante Branca 60cm", skuCode: "PFB-004", fromCatalog: true, quantity: 1, unitPrice: 90, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(72),
    paymentMethod: "Dinheiro",
    payoutForecast: hoursAgo(72),
    buyerName: "Cliente direto (WhatsApp)",
    address: "Retirada em loja",
  },
  {
    id: "ord_10",
    externalId: "ML-20260814190017",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Orgânico",
    status: "DELIVERED",
    shippingStage: "DELIVERED",
    shippingType: "Full",
    totalAmount: 349.7,
    feeAmount: 41.96,
    shippingCost: 0,
    taxAmount: 20.98,
    costAmount: 42.9 + 21.3 + 19.9,
    items: [
      { id: "it_10a", title: "Kit Organizador de Cozinha 5 Peças", skuCode: "KOC-001", fromCatalog: true, quantity: 1, unitPrice: 189.9, thumbnailColor: nextThumb() },
      { id: "it_10b", title: "Organizador de Geladeira Transparente", skuCode: "OGT-003", fromCatalog: true, quantity: 1, unitPrice: 79.9, thumbnailColor: nextThumb() },
      { id: "it_10c", title: "Cesto Organizador de Roupas", skuCode: "CER-005", fromCatalog: true, quantity: 1, unitPrice: 79.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(46),
    paymentMethod: "Cartão de crédito (parcelado 4x)",
    payoutForecast: daysFromNow(1),
    buyerName: "Marcos V.",
    address: "Campinas · SP",
  },
  {
    id: "ord_11",
    externalId: "SHP-88231190483",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    channel: "Orgânico",
    status: "IN_PREPARATION",
    shippingStage: "READY",
    shippingType: "Transportadora",
    totalAmount: 134.9,
    feeAmount: 16.19,
    shippingCost: 0,
    taxAmount: 8.09,
    costAmount: null,
    items: [
      { id: "it_11", title: "Prateleira Flutuante Branca 60cm", skuCode: null, fromCatalog: false, quantity: 1, unitPrice: 134.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(3),
    paymentMethod: "Cartão de crédito (à vista)",
    payoutForecast: daysFromNow(6),
    buyerName: "Renata C.",
    address: "Florianópolis · SC",
  },
  {
    id: "ord_12",
    externalId: "ML-20260813084455",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Ads",
    status: "SHIPPED",
    shippingStage: "IN_TRANSIT",
    shippingType: "Correios",
    totalAmount: 64.9,
    feeAmount: 7.79,
    // Frete grátis promocional que o seller absorveu: taxa + frete + imposto
    // + custo somam mais que o valor do pedido — outro exemplo de margem negativa.
    shippingCost: 35,
    taxAmount: 3.89,
    costAmount: 24.6,
    items: [
      { id: "it_12", title: "Porta Temperos Giratório", skuCode: "PTG-006", fromCatalog: true, quantity: 1, unitPrice: 64.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(40),
    buyerName: "Diego F.",
    paymentMethod: "Pix",
    payoutForecast: daysFromNow(2),
    address: "Goiânia · GO",
  },
  {
    id: "ord_13",
    externalId: "SHP-88176654201",
    provider: "SHOPEE",
    accountLabel: ACCOUNT_LABEL.SHOPEE,
    channel: "Orgânico",
    status: "PAID",
    shippingStage: null,
    shippingType: "Correios",
    totalAmount: 69.9,
    feeAmount: 8.39,
    shippingCost: 12.9,
    taxAmount: 4.19,
    costAmount: 21.3,
    items: [
      { id: "it_13", title: "Organizador de Geladeira Transparente", skuCode: "OGT-003", fromCatalog: true, quantity: 1, unitPrice: 69.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(7),
    paymentMethod: "Cartão de crédito (à vista)",
    payoutForecast: daysFromNow(5),
    buyerName: "Patrícia N.",
    address: "Vitória · ES",
  },
  {
    id: "ord_14",
    externalId: "ML-20260817203309",
    provider: "MERCADO_LIVRE",
    accountLabel: ACCOUNT_LABEL.MERCADO_LIVRE,
    channel: "Orgânico",
    status: "DELIVERED",
    shippingStage: "DELIVERED",
    shippingType: "Full",
    totalAmount: 379.8,
    feeAmount: 45.58,
    shippingCost: 0,
    taxAmount: 22.79,
    costAmount: null,
    items: [
      { id: "it_14", title: "Kit Organizador de Cozinha 5 Peças", skuCode: null, fromCatalog: false, quantity: 2, unitPrice: 189.9, thumbnailColor: nextThumb() },
    ],
    orderedAt: hoursAgo(4),
    paymentMethod: "Cartão de crédito (parcelado 6x)",
    payoutForecast: daysFromNow(2),
    buyerName: "Eduardo K.",
    address: "Brasília · DF",
  },
];

export const ORDER_STATUS_LABEL: Record<OrderStatus, string> = {
  PENDING: "Pendente",
  PAID: "Pago",
  IN_PREPARATION: "Em preparação",
  SHIPPED: "Enviado",
  DELIVERED: "Entregue",
  CANCELED: "Cancelado",
  RETURNED: "Devolvido",
};
